# Generated by Django 3.0.7 on 2020-06-24 06:21

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200624_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=articles.models.articles_image_path),
        ),
    ]
