# Generated by Django 3.0.7 on 2020-06-25 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommend_users',
            field=models.ManyToManyField(blank=True, related_name='recommend_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
